# Generated by Django 4.1.4 on 2022-12-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_alter_usemodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usemodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
