# Generated by Django 4.1.4 on 2022-12-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0005_alter_usemodel_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usemodel',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
    ]
